// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snvhvjckmdajedoelhet.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNudmh2amNrbWRhamVkb2VsaGV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MjM5NDUsImV4cCI6MjA3MTE5OTk0NX0.6O23aF4MfSciSZ2cCF5u_lvRvAZy14RXJJEiemlhM6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});