name: CI/CD Pipeline

on:
  push:
    branches: [ main, feat/fix-critical-audit ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint --if-present
      
    - name: Run tests
      run: npm test --if-present
      
    - name: Build project
      run: npm run build
      
    - name: Check build artifacts
      run: |
        if [ -d "dist" ]; then
          echo "✅ Build artifacts found in dist/"
          ls -la dist/
        elif [ -d "build" ]; then
          echo "✅ Build artifacts found in build/"
          ls -la build/
        else
          echo "✅ Build completed successfully"
          ls -la
        fi

  lighthouse:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build --if-present
      
    - name: Start local server
      run: |
        if command -v serve &> /dev/null; then
          npx serve -s . -l 3000 &
        else
          python3 -m http.server 3000 &
        fi
        sleep 5
      
    - name: Run Lighthouse CI
      run: |
        npm install -g @lhci/cli@0.12.x
        lhci autorun --upload.target=temporary-public-storage --collect.url=http://localhost:3000 --collect.url=http://localhost:3000?lang=no --collect.url=http://localhost:3000?lang=ua
      env:
        LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}